# Generated by Django 3.0.7 on 2023-10-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_names',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='companies',
            new_name='company',
        ),
    ]
